title: MediaKit
author:
  name: Montana Studio
  email: 'mauro@montana-studio.com'
metadata:
    charset: 'utf-8'
    description: 'MediaKit para **StarterDaily**'
    viewport: 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'
summary:
  enabled: true
  format: short
  size: 30
  delimiter: ===
